function validateEmail(){var a=!0;isValidEmail($("#account_form_email").val())?$.ajax({type:"POST",async:!1,url:"/storm/user/checkIfEmailExists.php",data:"EmailAddress="+encodeURIComponent($("#account_form_email").val()),success:function(b){"404"!=$.parseJSON(b).Status?(inputReset("email_confirm"),inputFailed("email"),$("#row_email").find(".row_msg").html(validate.emailInUse),$("#row_email").find(".account_form_col3").removeClass("pass"),a=!1):(inputPassed("email"),$("#account_form_email").val()!=
$("#account_form_email_confirm").val()?(inputFailed("email_confirm"),""!=$("#account_form_email_confirm").val()&&$("#row_email_confirm").find(".row_msg").html(validate.emailNoMatch),$("#row_email_confirm").find(".account_form_col3").removeClass("pass"),a=!1):inputPassed("email_confirm"))}}):(inputReset("email_confirm"),inputFailed("email"),$("#row_email").find(".row_msg").html(validate.invalidEmail),$("#row_email").find(".account_form_col3").removeClass("pass"),a=!1);return a}
function validateEmailNoConfirm(){var a=$("#row_email").find(".row_msg").attr("default");$("#row_email").find(".row_msg").html(a);var b=!0;if(isValidEmail($("#account_form_email").val())){var a=$("#account_form_email").attr("current"),c=$("#account_form_email").val();("undefined"==typeof a||!1==a||a!=c)&&$.ajax({type:"POST",async:!1,url:"/storm/user/checkIfEmailExists.php",data:"EmailAddress="+encodeURIComponent($("#account_form_email").val()),success:function(a){"404"!=$.parseJSON(a).Status?(inputReset("email_confirm"),
inputFailed("email"),$("#row_email").find(".row_msg").html(validate.emailInUse),$("#row_email").find(".account_form_col3").removeClass("pass"),b=!1):inputPassed("email")}})}else inputReset("email_confirm"),inputFailed("email"),$("#row_email").find(".row_msg").html(validate.invalidEmail),$("#row_email").find(".account_form_col3").removeClass("pass"),b=!1;return b}
function pwIntegrityCheck(a){var b=!1,c=!1,e=!0,f=!1;if(/\s/.test(a[0])||/\s/.test(a[a.length-1]))f=!0;if(8>a.length||256<a.length)e=!1;for(var d=0;d<a.length;d++)a.charAt(d),/[A-Z]/.test(a)&&(c=!0),/[0-9]/.test(a)&&(b=!0);return b?c?e?f?"passwordMsgSpace":"0":"passwordMsgLength":"passwordMsgCase":"passwordMsgDigit"}
function validatePassword(){var a=!0;"0"!==pwIntegrityCheck($("#account_form_password").val())?(inputReset("password_confirm"),inputFailed("password"),$("#row_password").find(".row_msg").addClass("l2"),$("#row_password").find(".account_form_col3").removeClass("pass"),a=!1):(inputPassed("password"),$("#account_form_password").val()!=$("#account_form_password_confirm").val()?(inputFailed("password_confirm"),$("#row_password_confirm").find(".row_msg").html(validate.passwordNoMatch),$("#row_password_confirm").find(".account_form_col3").removeClass("pass"),
a=!1):inputPassed("password_confirm"));return a}
function validatePasswordNoConfirm(){var a=!0;"0"!==pwIntegrityCheck($("#account_form_password").val())?(inputReset("password_confirm"),inputFailed("password"),$("#row_password").find(".row_msg").addClass("l2"),$("#row_password").find(".account_form_col3").removeClass("pass"),a=!1):pwIntegrityCheck($("#account_form_password").val())?inputPassed("password"):(inputReset("password_confirm"),inputFailed("password"),$("#row_password").find(".account_form_col3").removeClass("pass"),a=!1);return a}
function validateCountry(){if(""==$("#account_country").val())return $("#account_country-button").addClass("hasError"),inputFailed("country"),!1;$("#account_country-button").removeClass("hasError");inputPassed("country");return!0}
function validateBirthdate(){var a=$("#account_birthdate_day").val(),b=$("#account_birthdate_month").val()-1,c=$("#account_birthdate_year").val(),a=new Date(c,b,a);if(isValidDate(a))if(passedAgeCheck(a))$("#account_birthdate_month-button, #account_birthdate_day-button, #account_birthdate_year-button").removeClass("hasError"),inputPassed("birthdate");else return $("#row_birthdate").find(".row_msg").html(validate.ageReqNotMet),$("#account_birthdate_month-button, #account_birthdate_day-button, #account_birthdate_year-button").addClass("hasError"),
inputFailed("birthdate"),!1;else return $("#row_birthdate").find(".row_msg").html(validate.invalidBirthdate),$("#account_birthdate_month-button, #account_birthdate_day-button, #account_birthdate_year-button").addClass("hasError"),inputFailed("birthdate"),!1;return!0}
function validateCallsign(){var a=$("#row_callsign").find(".row_msg").attr("default");$("#row_callsign").find(".row_msg").html(a);var b=!0;""==$("#account_form_callsign").val()?(inputFailed("callsign"),b=!1):/[^a-zA-Z0-9_]/.test($("#account_form_callsign").val())?($("#row_callsign").find(".row_msg").html(validate.invalidCallsign),inputFailed("callsign"),b=!1):4>$("#account_form_callsign").val().length?($("#row_callsign").find(".row_msg").html(validate.callsignMinLength),inputFailed("callsign"),b=
!1):18<$("#account_form_callsign").val().length?($("#row_callsign").find(".row_msg").html(validate.callsignMaxLength),inputFailed("callsign"),b=!1):$("#account_form_callsign").val()!=$("#account_form_callsign_current").val()&&$.ajax({type:"POST",async:!1,url:"/storm/user/checkIfCallsignExists.php",data:"Callsign="+$("#account_form_callsign").val(),success:function(a){a=$.parseJSON(a);200<=a.Status&&300>a.Status?($("#row_callsign").find(".row_msg").html(validate.callsignInUse),inputFailed("callsign"),
b=!1):$.ajax({type:"POST",async:!1,url:"/storm/user/approveUserInput.php",data:"userInput="+$("#account_form_callsign").val(),success:function(a){a=$.parseJSON(a);200<=a.Status&&300>a.Status?inputPassed("callsign"):($("#row_callsign").find(".row_msg").html(validate.blacklistedCallsign),inputFailed("callsign"),b=!1)}})}});return b}
function validateOther(a){var b=!0;""!=$(".account_form input[code="+a+"]").val()?inputPassed(a):(inputFailed(a),$("#row_"+a).find(".account_form_col3").removeClass("pass"),b=!1);return b}
function isValidDate(a){var b=["09","04","06","11"];return"Invalid Date"!=a?-1<$.inArray($("#account_birthdate_month").val(),b)&&30<$("#account_birthdate_day").val()?!1:2==$("#account_birthdate_month").val()&&29<$("#account_birthdate_day").val()?!1:2==$("#account_birthdate_month").val()&&29==$("#account_birthdate_day").val()&&!1==isLeapYear($("#account_birthdate_year").val())?!1:!0:!1}function passedAgeCheck(a){return"Invalid Date"!=a?13>(new Date-a)/31536E6?!1:!0:!1}
function isLeapYear(a){return 0==a%4&&(0!=a%100||0==a%400)}function inputFailed(a){$("#row_"+a).addClass("hasError");$("#row_"+a).find(".row_msg").addClass("l2");$("#row_"+a).find(".account_form_col3").removeClass("pass").addClass("fail").show()}function inputPassed(a){$("#row_"+a).removeClass("hasError");$("#row_"+a).find(".row_msg").removeClass("l2");$("#row_"+a).find(".account_form_col3").addClass("pass").removeClass("fail").show()}
function inputReset(a){$("#row_"+a).removeClass("hasError");$("#row_"+a).find(".account_form_col3").removeClass("pass").removeClass("fail")}function resetSelects(){$("select.custom-select").each(function(){$(this).find('option[value="'+$(this).attr("default")+'"]').attr("selected","selected")})};
