function initPageContent(){var a=$("#page_header").attr("guide");activeNavs("game-guide",a);$("select.custom-select").selectmenu({style:"dropdown"});$("div.tile-menu li").hover(function(){$(this).find("div.label").animate({height:"85px"},100)},function(){$(this).find("div.label").animate({height:"35px"},100)});$("ul#mech-types li div.stat-bars div.stat-bar span.trigger").mouseenter(function(){$("span.stat-bar-tooltip").hide();$(this).parent().find("span.stat-bar-tooltip").show()});$("ul#mech-types li div.stat-bars div.stat-bar").mouseleave(function(){$(this).find("span.stat-bar-tooltip").hide()});
$(".stat-bars span.fill").each(function(){var c=$(this).attr("fill")/$(this).attr("max")*$(this).parent().width();$(this).show().animate({width:c},400,function(){})});$(".guide-active a").hover(function(){$(this).addClass("hover")},function(){$(this).removeClass("hover")});$(".guide-active").hover(function(){$(this).addClass("hover")},function(){$(this).removeClass("hover")});$("div.sort-by span.sort").click(function(){$("div.sort-by span").removeClass("active");$(this).addClass("active");var c=$(this).attr("by"),
b=$("ul.equipment-grid.weapons"),a=b.children("a");a.detach().sort(function(a,b){return"name"==c?$(a).find("div.weapon-name").html().toLowerCase()>$(b).find("div.weapon-name").html().toLowerCase()?1:-1:$(a).find("div.stat-bars").find("span.fill."+c).attr("fill")==$(b).find("div.stat-bars").find("span.fill."+c).attr("fill")?$(a).find("div.weapon-name").html().toLowerCase()>$(b).find("div.weapon-name").html().toLowerCase()?1:-1:$(a).find("div.stat-bars").find("span.fill."+c).attr("fill")<$(b).find("div.stat-bars").find("span.fill."+
c).attr("fill")?1:-1});b.append(a)});var e=0;$("div#guide_item_detail span.item-box").each(function(){e++;e<=$("#item-slots").html()&&$(this).addClass("full")});$(".spotlight-media").fancybox({openEffect:"none",closeEffect:"none",prevEffect:"none",nextEffect:"none",closeBtn:!1,wrapCSS:"popupBorder",padding:0,height:480,arrows:!1,helpers:{media:{},buttons:{}}});$("div.mech-video").on("click","a.spotlight-media",function(){sendVideoEvent($(this).attr("vidID"),"Played")});$("ul.faq-section-list").on("click",
"li",function(){$("div.faq-section-answer").hide().css("min-height",0);$("ul.faq-section-list li").removeClass("selected");$(this).addClass("selected");var c=$(this).find("span.answer").html();$(this).closest("div.faq-section").find("ul.faq-section-list").height();$(this).closest("div.faq-section").find("div.faq-section-answer").html(c).show();c=$(this).position().top;$("div#faq_answer_stem").css("top",c).show();var a=$(this).closest("div.faq-section").find("div.faq-section-answer").position().top+
$(this).closest("div.faq-section").find("div.faq-section-answer").height()+27;12>a-c&&$(this).closest("div.faq-section").find("div.faq-section-answer").css("min-height",$(this).closest("div.faq-section").find("div.faq-section-answer").height()+12-(a-c))});1==$("#active-map").length&&("gametype"==getMapView()?$("#active-map").lhpMegaImgViewer(getMapSettings($("#active-map").attr("showMap"),getMapView(),0.44875549048316254,681,681),$("#active-map").attr("showMap")+"_poi_"+getGameMode()):"zones"==getMapView()&&
$("#active-map").lhpMegaImgViewer(getMapSettings($("#active-map").attr("showMap"),getMapView(),0.44875549048316254,681,681),$("#active-map").attr("showMap")+"_zones"),$("ul#map-buttons li[mapid="+$("#active-map").attr("showMap")+"]").addClass("active"),$("#map-scale").slider({orientation:"vertical",range:"min",min:0.44875549048316254,max:1,step:0.01,slide:function(c,a){$("#active-map").lhpMegaImgViewer("setPosition","","",a.value)}}),$("div#map-enlarge a").attr("href","/images/game-guide/maps/hd/"+
$("#active-map").attr("showMap")+".jpg"),$("li.map-change-layer").click(function(){$("div#map-enlarge a").attr("href","/images/game-guide/maps/hd/"+$(this).attr("mapID")+".jpg");$("ul#map-buttons li").removeClass("active");$("#active-map").attr("showMap",$(this).attr("mapID"));$("div#map-poi-info").find("div.current").hide();$("div#map-poi-info").find("div.default").show();var a=$("#active-map").attr("scale"),b=$("#active-map").lhpMegaImgViewer("getCurrentState").xPosInCenter,d=$("#active-map").lhpMegaImgViewer("getCurrentState").yPosInCenter;
"gametype"==getMapView()?$("#active-map").lhpMegaImgViewer("destroy").lhpMegaImgViewer(getMapSettings($(this).attr("mapID"),"gametype",a,b,d),$(this).attr("mapID")+"_poi_"+getGameMode()):"zones"==getMapView()?$("#active-map").lhpMegaImgViewer("destroy").lhpMegaImgViewer(getMapSettings($(this).attr("mapID"),"zones",a,b,d),$(this).attr("mapID")+"_zones"):$("#active-map").lhpMegaImgViewer("destroy").lhpMegaImgViewer(getMapSettings($(this).attr("mapID"),getMapView(),a,b,d));$("ul#map-buttons li[mapid="+
$("#active-map").attr("showMap")+"]").addClass("active")}),$("select.map-change-menu").change(function(){console.log($("select#map-views-menu").val());$("div#map-poi-info").find("div.current").hide();$("div#map-poi-info").find("div.default").show();var a=$("#active-map").attr("showMap"),b=$("#active-map").attr("scale"),d=$("#active-map").lhpMegaImgViewer("getCurrentState").xPosInCenter,f=$("#active-map").lhpMegaImgViewer("getCurrentState").yPosInCenter;if("gametype"==$("select#map-views-menu").val()){$("div#map-poi-info").show();
$("a#map-gamemodes-menu-button").show();$("span#map-gamemodes-solo").show();if("undefined"!=typeof $("#map-gamemodes-menu").val())var e=$("#map-gamemodes-menu").val();else"undefined"!=typeof $("#map-gamemodes-solo").attr("mode")&&(e=$("#map-gamemodes-solo").attr("mode"));$("#active-map").lhpMegaImgViewer("destroy").lhpMegaImgViewer(getMapSettings(a,"gametype",b,d,f),a+"_poi_"+e)}else"zones"==$("select#map-views-menu").val()?($("div#map-poi-info").show(),$("a#map-gamemodes-menu-button").hide(),$("span#map-gamemodes-solo").hide(),
$("ul.ui-widget li").removeClass("ui-selectmenu-item-focus"),$("select#map-gamemodes-menu").selectmenu("index",0),$("#active-map").lhpMegaImgViewer("destroy").lhpMegaImgViewer(getMapSettings(a,"zones",b,d,f),a+"_zones")):($("div#map-poi-info").hide(),$("a#map-gamemodes-menu-button").hide(),$("span#map-gamemodes-solo").hide(),$("ul.ui-widget li").removeClass("ui-selectmenu-item-focus"),$("select#map-gamemodes-menu").selectmenu("index",0),$("#active-map").lhpMegaImgViewer("destroy").lhpMegaImgViewer(getMapSettings(a,
$("select#map-views-menu").val(),b,d,f)))}))}
function getMapSettings(a,e,c,b,d){var f=a.replace(/[lLbB]\d{1}/,"");return{viewportWidth:"100%",viewportHeight:"100%",fitToViewportShortSide:!0,contentSizeOver100:!1,startScale:c,startX:b,startY:d,animTime:0,draggInertia:0,contentUrl:"no-overlay"==e||"gametype"==e?"/images/game-guide/maps/"+f+"/overheads/"+a+".jpg":"/images/game-guide/maps/"+f+"/overheads/"+a+"_"+e+".jpg",intNavEnable:!1,intNavPos:"B",intNavAutoHide:!1,intNavMoveDownBtt:!1,intNavMoveUpBtt:!1,intNavMoveRightBtt:!1,intNavMoveLeftBtt:!1,
intNavZoomBtt:!1,intNavUnzoomBtt:!1,intNavFitToViewportBtt:!1,intNavFullSizeBtt:!1,intNavBttSizeRation:1,mapEnable:!0,mapThumb:"/images/game-guide/maps/"+f+"/overheads/"+a+"_thumb.jpg",mapPos:"BL",popupShowAction:"click",testMode:!1}}function getMapDir(a){return a.replace(/[lLbB]\d{1}/,"")}function getMapView(){if(0!=$("select#map-views-menu").length)var a=$("select#map-views-menu").val();else 0!=$("span#map-views-solo").length&&(a=$("span#map-views-solo").attr("view"));return a}
function getGameMode(){if(0!=$("select#map-gamemodes-menu").length)var a=$("select#map-gamemodes-menu").val();else 0!=$("span#map-gamemodes-solo").length&&(a=$("span#map-gamemodes-solo").attr("mode"));return a};
